from meya.zendesk.support.payload.attachment import ZendeskSupportAttachment
from meya.zendesk.support.payload.user import ZendeskSupportUserGet
from meya.zendesk.support.payload.user import ZendeskSupportUserRole


def test_user_get_from_dict_agent():
    assert ZendeskSupportUserGet.from_dict(
        {
            "id": 114318908893,
            "url": "https://d3v-meya.zendesk.com/api/v2/users/114318908893.json",
            "name": "Roeland van Nieuwkerk",
            "email": "roeland@meya.ai",
            "created_at": "2017-06-22T18:07:50Z",
            "updated_at": "2020-07-16T20:41:34Z",
            "time_zone": "Arizona",
            "iana_time_zone": "America/Phoenix",
            "phone": None,
            "shared_phone_number": None,
            "photo": {
                "url": "https://d3v-meya.zendesk.com/api/v2/attachments/361651116193.json",
                "id": 361651116193,
                "file_name": "avataaars__2_.png",
                "content_url": "https://d3v-meya.zendesk.com/system/photos/3616/5111/6193/avataaars__2_.png",
                "mapped_content_url": "https://d3v-meya.zendesk.com/system/photos/3616/5111/6193/avataaars__2_.png",
                "content_type": "image/png",
                "size": 6500,
                "width": 80,
                "height": 85,
                "inline": False,
                "deleted": False,
                "thumbnails": [
                    {
                        "url": "https://d3v-meya.zendesk.com/api/v2/attachments/361651116213.json",
                        "id": 361651116213,
                        "file_name": "avataaars__2__thumb.png",
                        "content_url": "https://d3v-meya.zendesk.com/system/photos/3616/5111/6193/avataaars__2__thumb.png",
                        "mapped_content_url": "https://d3v-meya.zendesk.com/system/photos/3616/5111/6193/avataaars__2__thumb.png",
                        "content_type": "image/png",
                        "size": 2120,
                        "width": 30,
                        "height": 32,
                        "inline": False,
                        "deleted": False,
                    }
                ],
            },
            "locale_id": 1,
            "locale": "en-US",
            "organization_id": None,
            "role": "agent",
            "verified": True,
            "external_id": "UMDQ9OrheaI",
            "tags": [],
            "alias": "Roeland van N.",
            "active": True,
            "shared": False,
            "shared_agent": False,
            "last_login_at": "2020-07-16T19:35:45Z",
            "two_factor_auth_enabled": None,
            "signature": "",
            "details": "",
            "notes": "",
            "role_type": 0,
            "custom_role_id": 114094399394,
            "moderator": False,
            "ticket_restriction": None,
            "only_private_comments": False,
            "restricted_agent": False,
            "suspended": False,
            "chat_only": False,
            "default_group_id": 114094302554,
            "report_csv": False,
            "user_fields": {"favcolor": None},
        }
    ) == ZendeskSupportUserGet(
        alias="Roeland van N.",
        created_at="2017-06-22T18:07:50Z",
        details="",
        email="roeland@meya.ai",
        external_id="UMDQ9OrheaI",
        id=114318908893,
        name="Roeland van Nieuwkerk",
        photo=ZendeskSupportAttachment(
            content_type="image/png",
            content_url="https://d3v-meya.zendesk.com/system/photos/3616/5111/6193/avataaars__2_.png",
            file_name="avataaars__2_.png",
            id=361651116193,
        ),
        role=ZendeskSupportUserRole.AGENT,
        updated_at="2020-07-16T20:41:34Z",
        user_fields={"favcolor": None},
        verified=True,
    )


def test_user_get_from_dict_end_user():
    assert ZendeskSupportUserGet.from_dict(
        {
            "id": 416025657633,
            "url": "https://d3v-meya.zendesk.com/api/v2/users/416025657633.json",
            "name": "NAME",
            "role": "end-user",
            "tags": [],
            "alias": None,
            "email": None,
            "notes": None,
            "phone": None,
            "photo": None,
            "active": True,
            "locale": "en-US",
            "shared": False,
            "details": None,
            "verified": False,
            "chat_only": False,
            "locale_id": 1,
            "moderator": False,
            "role_type": None,
            "signature": None,
            "suspended": False,
            "time_zone": "Arizona",
            "created_at": "2020-07-15T19:04:37Z",
            "report_csv": False,
            "updated_at": "2020-07-15T19:04:37Z",
            "external_id": "u-53e5eab4c0264d09bc977e34016e3495",
            "user_fields": {
                "bluetooth_connected": True,
                "devices_owned": 4,
                "favcolor": None,
                "firmware_version": "4.2.1",
                "first_purchase_date": "2020-07-15T00:00:00+00:00",
                "personal_bio": "Hello\nEveryone\nLet's\nLoop\nOn",
                "phone_brand": "android",
                "phone_model": "Samsung Galaxy",
                "phone_weight": 2.1,
            },
            "shared_agent": False,
            "last_login_at": None,
            "custom_role_id": None,
            "iana_time_zone": "America/Phoenix",
            "organization_id": None,
            "default_group_id": None,
            "restricted_agent": True,
            "ticket_restriction": "requested",
            "shared_phone_number": None,
            "only_private_comments": False,
            "two_factor_auth_enabled": False,
        }
    ) == ZendeskSupportUserGet(
        external_id="u-53e5eab4c0264d09bc977e34016e3495",
        name="NAME",
        id=416025657633,
        role=ZendeskSupportUserRole.END_USER,
        created_at="2020-07-15T19:04:37Z",
        updated_at="2020-07-15T19:04:37Z",
        verified=False,
        user_fields={
            "bluetooth_connected": True,
            "devices_owned": 4,
            "favcolor": None,
            "firmware_version": "4.2.1",
            "first_purchase_date": "2020-07-15T00:00:00+00:00",
            "personal_bio": "Hello\nEveryone\nLet's\nLoop\nOn",
            "phone_brand": "android",
            "phone_model": "Samsung Galaxy",
            "phone_weight": 2.1,
        },
    )
