from meya.twilio.voice.payload.call import TwilioVoiceCallPayload
from meya.twilio.voice.payload.call import TwilioVoiceWebhookDirection


def test_ticket_get_from_dict():
    assert TwilioVoiceCallPayload.from_dict(
        {
            "date_updated": None,
            "price_unit": "USD",
            "parent_call_sid": None,
            "caller_name": None,
            "duration": None,
            "from": "+1226",
            "to": "+554799",
            "annotation": None,
            "answered_by": None,
            "sid": "12312asdasdsadas",
            "queue_time": "0",
            "price": None,
            "api_version": "2010-04-01",
            "status": "queued",
            "direction": "outbound-api",
            "start_time": None,
            "date_created": None,
            "from_formatted": "(226) 806",
            "group_sid": None,
            "trunk_sid": None,
            "forwarded_from": None,
            "uri": "/2010-04-01/Accounts//Calls/.json",
            "account_sid": "12312312321",
            "end_time": None,
            "to_formatted": "+554799",
            "phone_number_sid": "12dsadasdads",
            "subresource_uris": {
                "notifications": "/2010-04-01/Accounts//Calls//Notifications.json",
                "recordings": "/2010-04-01/Accounts//Calls//Recordings.json",
                "payments": "/2010-04-01/Accounts//Calls//Payments.json",
                "feedback": "/2010-04-01/Accounts//Calls//Feedback.json",
                "events": "/2010-04-01/Accounts//Calls//Events.json",
                "feedback_summaries": "/2010-04-01/Accounts//Calls/FeedbackSummary.json",
            },
        }
    ) == TwilioVoiceCallPayload(
        to="+554799",
        sid="12312asdasdsadas",
        uri="/2010-04-01/Accounts//Calls/.json",
        from_="+1226",
        status="queued",
        direction=TwilioVoiceWebhookDirection.OUTBOUND_API,
        price_unit="USD",
        queue_time="0",
        start_time=None,
        account_sid="12312312321",
        api_version="2010-04-01",
        to_formatted="+554799",
        forwarded_from=None,
        from_formatted="(226) 806",
        parent_call_sid=None,
        phone_number_sid="12dsadasdads",
        subresource_uris={
            "notifications": "/2010-04-01/Accounts//Calls//Notifications.json",
            "recordings": "/2010-04-01/Accounts//Calls//Recordings.json",
            "payments": "/2010-04-01/Accounts//Calls//Payments.json",
            "feedback": "/2010-04-01/Accounts//Calls//Feedback.json",
            "events": "/2010-04-01/Accounts//Calls//Events.json",
            "feedback_summaries": "/2010-04-01/Accounts//Calls/FeedbackSummary.json",
        },
        caller_name=None,
        date_created=None,
        date_updated=None,
        answered_by=None,
        group_sid=None,
        trunk_sid=None,
        annotation=None,
        duration=None,
        end_time=None,
        price=None,
    )
