from meya.zendesk.help_center.payload.article import ZendeskHelpCenterArticle
from meya.zendesk.help_center.payload.article import (
    ZendeskHelpCenterArticlesResponse,
)
from meya.zendesk.help_center.payload.query import (
    ZendeskHelpCenterArticleSearchResponse,
)
from meya.zendesk.help_center.payload.query import (
    ZendeskHelpCenterSearchResponse,
)


def test_articles_payload():
    assert ZendeskHelpCenterArticlesResponse.from_dict(
        {
            "count": 6,
            "next_page": None,
            "page": 1,
            "page_count": 1,
            "per_page": 30,
            "previous_page": None,
            "articles": [
                {
                    "id": 360052070733,
                    "url": "https://d3v-meya.zendesk.com/api/v2/help_center/en-us/articles/360052070733.json",
                    "html_url": "https://d3v-meya.zendesk.com/hc/en-us/articles/360052070733-New-article",
                    "author_id": 114318908893,
                    "comments_disabled": False,
                    "draft": True,
                    "promoted": True,
                    "position": 0,
                    "vote_sum": 0,
                    "vote_count": 0,
                    "section_id": 360007795853,
                    "created_at": "2020-07-21T15:22:53Z",
                    "updated_at": "2020-07-21T15:22:53Z",
                    "name": "New article",
                    "title": "New article",
                    "source_locale": "en-us",
                    "locale": "en-us",
                    "outdated": False,
                    "outdated_locales": [],
                    "edited_at": "2020-07-21T15:22:53Z",
                    "user_segment_id": None,
                    "permission_group_id": 1718433,
                    "label_names": [],
                    "body": "<p>Article text....</p>",
                },
                {
                    "id": 360045161313,
                    "url": "https://d3v-meya.zendesk.com/api/v2/help_center/en-us/articles/360045161313.json",
                    "html_url": "https://d3v-meya.zendesk.com/hc/en-us/articles/360045161313-How-can-agents-leverage-knowledge-to-help-customers-",
                    "author_id": 114314414734,
                    "comments_disabled": False,
                    "draft": False,
                    "promoted": False,
                    "position": 0,
                    "vote_sum": 0,
                    "vote_count": 0,
                    "section_id": 360007795853,
                    "created_at": "2020-03-17T16:56:27Z",
                    "updated_at": "2020-03-17T16:56:27Z",
                    "name": "How can agents leverage knowledge to help customers?",
                    "title": "How can agents leverage knowledge to help customers?",
                    "source_locale": "en-us",
                    "locale": "en-us",
                    "outdated": False,
                    "outdated_locales": [],
                    "edited_at": "2020-03-17T16:56:27Z",
                    "user_segment_id": None,
                    "permission_group_id": 1718433,
                    "label_names": [],
                    "body": '<p>You can use our <a href="https://support.zendesk.com/hc/en-us/articles/115012706488" target="_blank">Knowledge Capture app</a> to leverage your team’s collective knowledge.</p>\n<p>Using the app, agents can:\n</p><ul>\n  <li>Search the Help Center without leaving the ticket</li>\n  <li>Insert links to relevant Help Center articles in ticket comments</li>\n  <li>Add inline feedback to existing articles that need updates</li>\n  <li>Create new articles while answering tickets using a pre-defined template</li>\n</ul>\n\n\n<p>Agents never have to leave the ticket interface to share, flag, or create knowledge, so they can help the customer, while also improving your self-service offerings for other customers.</p>\n\n<p>To get started, see our <a href="https://support.zendesk.com/hc/en-us/articles/360001975088" target="_blank">Knowledge Capture documentation</a>.</p>\n\n<p>And before your agents can start creating new knowledge directly from tickets, you’ll need to <a href="https://support.zendesk.com/hc/en-us/articles/115002374987" target="_blank">create a template</a> for them to use. To help you along, we’ve provided some template ideas below. You can copy and paste any sample template below into a new article, add the <strong>KCTemplate</strong> label to the article, and you’ll be all set.</p>\n\n<h4>Q&amp;A template:</h4>\n\n<blockquote>\n\n<p>\n</p>\n<h3>[Title]</h3>\n\n\n<p>\n</p>\n<h3>Question</h3>\nwrite the question here.\n\n\n<p>\n</p>\n<h3>Answer</h3>\nwrite the answer here.\n\n\n</blockquote>\n\n<h4>Solution template:</h4>\n\n<blockquote>\n\n<p>\n</p>\n<h3>[Title]</h3>\n\n\n<p>\n</p>\n<h3>Symptoms</h3>\nwrite the symptoms here.\n\n\n<p>\n</p>\n<h3>Resolution</h3>\nwrite the resolution here.\n\n\n<p>\n</p>\n<h3>Cause</h3>\nwrite the cause here.\n\n\n</blockquote>\n\n<h4>How-to template:</h4>\n\n<blockquote>\n\n<p>\n</p>\n<h3>[Title]</h3>\n\n\n<p>\n</p>\n<h3>Objective</h3>\nwrite the purpose or task here.\n\n\n<p>\n</p>\n<h3>Procedure</h3>\nwrite the steps here.\n\n\n</blockquote>\n',
                },
            ],
            "sort_by": "position",
            "sort_order": "asc",
        }
    ) == ZendeskHelpCenterArticlesResponse(
        count=6,
        next_page=None,
        page=1,
        page_count=1,
        per_page=30,
        previous_page=None,
        sort_by="position",
        sort_order="asc",
        articles=[
            ZendeskHelpCenterArticle(
                id=360052070733,
                url="https://d3v-meya.zendesk.com/api/v2/help_center/en-us/articles/360052070733.json",
                html_url="https://d3v-meya.zendesk.com/hc/en-us/articles/360052070733-New-article",
                author_id=114318908893,
                comments_disabled=False,
                draft=True,
                promoted=True,
                position=0,
                vote_sum=0,
                vote_count=0,
                section_id=360007795853,
                created_at="2020-07-21T15:22:53Z",
                updated_at="2020-07-21T15:22:53Z",
                name="New article",
                title="New article",
                source_locale="en-us",
                locale="en-us",
                outdated=False,
                outdated_locales=[],
                edited_at="2020-07-21T15:22:53Z",
                user_segment_id=None,
                permission_group_id=1718433,
                label_names=[],
                body="<p>Article text....</p>",
            ),
            ZendeskHelpCenterArticle(
                id=360045161313,
                url="https://d3v-meya.zendesk.com/api/v2/help_center/en-us/articles/360045161313.json",
                html_url="https://d3v-meya.zendesk.com/hc/en-us/articles/360045161313-How-can-agents-leverage-knowledge-to-help-customers-",
                author_id=114314414734,
                comments_disabled=False,
                draft=False,
                promoted=False,
                position=0,
                vote_sum=0,
                vote_count=0,
                section_id=360007795853,
                created_at="2020-03-17T16:56:27Z",
                updated_at="2020-03-17T16:56:27Z",
                name="How can agents leverage knowledge to help customers?",
                title="How can agents leverage knowledge to help customers?",
                source_locale="en-us",
                locale="en-us",
                outdated=False,
                outdated_locales=[],
                edited_at="2020-03-17T16:56:27Z",
                user_segment_id=None,
                permission_group_id=1718433,
                label_names=[],
                body='<p>You can use our <a href="https://support.zendesk.com/hc/en-us/articles/115012706488" target="_blank">Knowledge Capture app</a> to leverage your team’s collective knowledge.</p>\n<p>Using the app, agents can:\n</p><ul>\n  <li>Search the Help Center without leaving the ticket</li>\n  <li>Insert links to relevant Help Center articles in ticket comments</li>\n  <li>Add inline feedback to existing articles that need updates</li>\n  <li>Create new articles while answering tickets using a pre-defined template</li>\n</ul>\n\n\n<p>Agents never have to leave the ticket interface to share, flag, or create knowledge, so they can help the customer, while also improving your self-service offerings for other customers.</p>\n\n<p>To get started, see our <a href="https://support.zendesk.com/hc/en-us/articles/360001975088" target="_blank">Knowledge Capture documentation</a>.</p>\n\n<p>And before your agents can start creating new knowledge directly from tickets, you’ll need to <a href="https://support.zendesk.com/hc/en-us/articles/115002374987" target="_blank">create a template</a> for them to use. To help you along, we’ve provided some template ideas below. You can copy and paste any sample template below into a new article, add the <strong>KCTemplate</strong> label to the article, and you’ll be all set.</p>\n\n<h4>Q&amp;A template:</h4>\n\n<blockquote>\n\n<p>\n</p>\n<h3>[Title]</h3>\n\n\n<p>\n</p>\n<h3>Question</h3>\nwrite the question here.\n\n\n<p>\n</p>\n<h3>Answer</h3>\nwrite the answer here.\n\n\n</blockquote>\n\n<h4>Solution template:</h4>\n\n<blockquote>\n\n<p>\n</p>\n<h3>[Title]</h3>\n\n\n<p>\n</p>\n<h3>Symptoms</h3>\nwrite the symptoms here.\n\n\n<p>\n</p>\n<h3>Resolution</h3>\nwrite the resolution here.\n\n\n<p>\n</p>\n<h3>Cause</h3>\nwrite the cause here.\n\n\n</blockquote>\n\n<h4>How-to template:</h4>\n\n<blockquote>\n\n<p>\n</p>\n<h3>[Title]</h3>\n\n\n<p>\n</p>\n<h3>Objective</h3>\nwrite the purpose or task here.\n\n\n<p>\n</p>\n<h3>Procedure</h3>\nwrite the steps here.\n\n\n</blockquote>\n',
            ),
        ],
    )


def test_search_response():
    assert ZendeskHelpCenterSearchResponse.from_dict(
        {
            "count": 5,
            "next_page": None,
            "page": 1,
            "page_count": 1,
            "per_page": 25,
            "previous_page": None,
            "results": [
                {
                    "id": 360045161233,
                    "url": "https://d3v-meya.zendesk.com/api/v2/help_center/en-us/articles/360045161233.json",
                    "html_url": "https://d3v-meya.zendesk.com/hc/en-us/articles/360045161233-Welcome-to-your-Help-Center-",
                    "author_id": 114314414734,
                    "comments_disabled": False,
                    "draft": False,
                    "promoted": False,
                    "position": 0,
                    "vote_sum": 0,
                    "vote_count": 0,
                    "section_id": 360007795833,
                    "created_at": "2020-03-17T16:56:26Z",
                    "updated_at": "2020-03-17T16:56:26Z",
                    "name": "Welcome to your Help Center!",
                    "title": "Welcome to your Help Center!",
                    "source_locale": "en-us",
                    "locale": "en-us",
                    "outdated": False,
                    "outdated_locales": [],
                    "edited_at": "2020-03-17T16:56:26Z",
                    "user_segment_id": None,
                    "permission_group_id": 1718433,
                    "label_names": [],
                    "body": '<p>You\'re looking at your new <a href="https://www.zendesk.com/self-service" target="_blank">Help Center</a>. We populated it with placeholder content to help you get started. Feel free to edit or delete this content.</p>\n\n<p>The Help Center is designed to provide a complete self-service support option for your customers. The Help Center contains: a knowledge base and, on Guide Professional and Enterprise, a Customer Portal for support requests. You can also add a community to your Help Center if you have Zendesk Gather.</p>\n\n<p>Your customers can search for knowledge base articles to learn a task or search the community, if available, to ask fellow users questions. If your customers can\'t find an answer, they can submit a support request.</p>\n\n<p>For more information, see <a href="https://support.zendesk.com/hc/en-us/articles/203664386" target="_blank">Help Center guide for end users</a>.</p><p>Each user has a Help Center profile (Guide Professional and Enterprise), so your Help Center users can get to know one another better. Profiles contain relevant information about the user, along with their activities and contributions.</p>',
                    "snippet": "You're looking at your new <em>Help</em> Center. We populated it with placeholder content to <em>help</em> you get started.",
                    "result_type": "article",
                },
                {
                    "id": 360045161273,
                    "url": "https://d3v-meya.zendesk.com/api/v2/help_center/en-us/articles/360045161273.json",
                    "html_url": "https://d3v-meya.zendesk.com/hc/en-us/articles/360045161273-How-do-I-customize-my-Help-Center-",
                    "author_id": 114314414734,
                    "comments_disabled": False,
                    "draft": False,
                    "promoted": False,
                    "position": 0,
                    "vote_sum": 0,
                    "vote_count": 0,
                    "section_id": 360007795853,
                    "created_at": "2020-03-17T16:56:27Z",
                    "updated_at": "2020-03-17T16:56:27Z",
                    "name": "How do I customize my Help Center?",
                    "title": "How do I customize my Help Center?",
                    "source_locale": "en-us",
                    "locale": "en-us",
                    "outdated": False,
                    "outdated_locales": [],
                    "edited_at": "2020-03-17T16:56:27Z",
                    "user_segment_id": None,
                    "permission_group_id": 1718433,
                    "label_names": [],
                    "body": '<p>You can modify the look and feel of your Help Center by changing colors and fonts. See <a href="https://support.zendesk.com/hc/en-us/articles/206177737" target="_blank">Branding your Help Center</a> to learn how.</p>\n\n<p>You can also change the design of your Help Center. If you\'re comfortable working with page code, you can dig in to the site\'s HTML, CSS, and Javascript to customize your theme. To get started, see <a href="https://support.zendesk.com/hc/en-us/articles/203664326" target="_blank">Customizing the Help Center</a>.</p>',
                    "snippet": "You can also change the design of your <em>Help</em> Center.",
                    "result_type": "article",
                },
            ],
        }
    ) == ZendeskHelpCenterSearchResponse(
        count=5,
        next_page=None,
        page=1,
        page_count=1,
        per_page=25,
        previous_page=None,
        results=[
            ZendeskHelpCenterArticleSearchResponse(
                id=360045161233,
                url="https://d3v-meya.zendesk.com/api/v2/help_center/en-us/articles/360045161233.json",
                html_url="https://d3v-meya.zendesk.com/hc/en-us/articles/360045161233-Welcome-to-your-Help-Center-",
                author_id=114314414734,
                comments_disabled=False,
                draft=False,
                promoted=False,
                position=0,
                vote_sum=0,
                vote_count=0,
                section_id=360007795833,
                created_at="2020-03-17T16:56:26Z",
                updated_at="2020-03-17T16:56:26Z",
                name="Welcome to your Help Center!",
                title="Welcome to your Help Center!",
                source_locale="en-us",
                locale="en-us",
                outdated=False,
                outdated_locales=[],
                edited_at="2020-03-17T16:56:26Z",
                user_segment_id=None,
                permission_group_id=1718433,
                label_names=[],
                body='<p>You\'re looking at your new <a href="https://www.zendesk.com/self-service" target="_blank">Help Center</a>. We populated it with placeholder content to help you get started. Feel free to edit or delete this content.</p>\n\n<p>The Help Center is designed to provide a complete self-service support option for your customers. The Help Center contains: a knowledge base and, on Guide Professional and Enterprise, a Customer Portal for support requests. You can also add a community to your Help Center if you have Zendesk Gather.</p>\n\n<p>Your customers can search for knowledge base articles to learn a task or search the community, if available, to ask fellow users questions. If your customers can\'t find an answer, they can submit a support request.</p>\n\n<p>For more information, see <a href="https://support.zendesk.com/hc/en-us/articles/203664386" target="_blank">Help Center guide for end users</a>.</p><p>Each user has a Help Center profile (Guide Professional and Enterprise), so your Help Center users can get to know one another better. Profiles contain relevant information about the user, along with their activities and contributions.</p>',
                snippet="You're looking at your new <em>Help</em> Center. We populated it with placeholder content to <em>help</em> you get started.",
                result_type="article",
            ),
            ZendeskHelpCenterArticleSearchResponse(
                id=360045161273,
                url="https://d3v-meya.zendesk.com/api/v2/help_center/en-us/articles/360045161273.json",
                html_url="https://d3v-meya.zendesk.com/hc/en-us/articles/360045161273-How-do-I-customize-my-Help-Center-",
                author_id=114314414734,
                comments_disabled=False,
                draft=False,
                promoted=False,
                position=0,
                vote_sum=0,
                vote_count=0,
                section_id=360007795853,
                created_at="2020-03-17T16:56:27Z",
                updated_at="2020-03-17T16:56:27Z",
                name="How do I customize my Help Center?",
                title="How do I customize my Help Center?",
                source_locale="en-us",
                locale="en-us",
                outdated=False,
                outdated_locales=[],
                edited_at="2020-03-17T16:56:27Z",
                user_segment_id=None,
                permission_group_id=1718433,
                label_names=[],
                body='<p>You can modify the look and feel of your Help Center by changing colors and fonts. See <a href="https://support.zendesk.com/hc/en-us/articles/206177737" target="_blank">Branding your Help Center</a> to learn how.</p>\n\n<p>You can also change the design of your Help Center. If you\'re comfortable working with page code, you can dig in to the site\'s HTML, CSS, and Javascript to customize your theme. To get started, see <a href="https://support.zendesk.com/hc/en-us/articles/203664326" target="_blank">Customizing the Help Center</a>.</p>',
                snippet="You can also change the design of your <em>Help</em> Center.",
                result_type="article",
            ),
        ],
    )
