from random import Random


class Naminator:
    _adjectives = [
        "Active",
        "Ancient",
        "Autumn",
        "Billowing",
        "Bitter",
        "Black",
        "Blue",
        "Bold",
        "Broad",
        "Beautiful",
        "Calm",
        "Cold",
        "Cool",
        "Crimson",
        "Curly",
        "Delightful",
        "Dark",
        "Dawn",
        "Delicate",
        "Divine",
        "Dry",
        "Empty",
        "Falling",
        "Fancy",
        "Flat",
        "Floral",
        "Fragrant",
        "Frosty",
        "Gentle",
        "Green",
        "Hidden",
        "Holy",
        "Icy",
        "Jolly",
        "Late",
        "Lingering",
        "Lovely",
        "Lively",
        "Long",
        "Lucky",
        "Misty",
        "Morning",
        "Muddy",
        "Mute",
        "Nameless",
        "Noisy",
        "Odd",
        "Old",
        "Orange",
        "Patient",
        "Plain",
        "Polished",
        "Proud",
        "Purple",
        "Quiet",
        "Rapid",
        "Raspy",
        "Red",
        "Restless",
        "Rough",
        "Round",
        "Royal",
        "Shiny",
        "Silly",
        "Simple",
        "Silent",
        "Small",
        "Snowy",
        "Soft",
        "Solitary",
        "Sparkling",
        "Spring",
        "Square",
        "Steep",
        "Still",
        "Summer",
        "Super",
        "Sweet",
        "Thoughtful",
        "Tight",
        "Tiny",
        "Twilight",
        "Wandering",
        "Weathered",
        "White",
        "Wild",
        "Winter",
        "Wispy",
        "Yellow",
        "Young",
    ]

    _nouns = [
        "Art",
        "Band",
        "Bottle",
        "Base",
        "Bird",
        "Block",
        "Boat",
        "Bonus",
        "Bread",
        "Breeze",
        "Brook",
        "Bush",
        "Butterfly",
        "Cake",
        "Cell",
        "Cherry",
        "Cloud",
        "Credit",
        "Darkness",
        "Dawn",
        "Dew",
        "Disk",
        "Dream",
        "Dust",
        "Feather",
        "Field",
        "Fire",
        "Firefly",
        "Flower",
        "Fog",
        "Forest",
        "Frog",
        "Frost",
        "Glade",
        "Glitter",
        "Grass",
        "Hall",
        "Hat",
        "Haze",
        "Heart",
        "Hill",
        "King",
        "Lab",
        "Lake",
        "Leaf",
        "Limit",
        "Math",
        "Meadow",
        "Mode",
        "Moon",
        "Morning",
        "Mountain",
        "Mouse",
        "Mud",
        "Night",
        "Paper",
        "Pine",
        "Poetry",
        "Pond",
        "Queen",
        "Rain",
        "Recipe",
        "Resonance",
        "Rice",
        "River",
        "Salad",
        "Scene",
        "Sea",
        "Shadow",
        "Shape",
        "Silence",
        "Sky",
        "Smoke",
        "Snow",
        "Snowflake",
        "Sound",
        "Star",
        "Sun",
        "Sun",
        "Sunset",
        "Surf",
        "Term",
        "Thunder",
        "Tooth",
        "Tree",
        "Truth",
        "Union",
        "Umbrella",
        "Violet",
        "Voice",
        "Water",
        "Waterfall",
        "Wave",
        "Wildflower",
        "Wind",
        "Wall",
    ]

    def __init__(self, seed=None, adjectives=None, nouns=None):
        if adjectives is not None:
            self._adjectives = adjectives
        if nouns is not None:
            self._nouns = nouns
        self.random = Random(seed)

    def naminate(self, delimiter=" "):
        adjective = self._random_element(self._adjectives)
        noun = self._random_element(self._nouns)
        sections = [adjective, noun]
        return delimiter.join(filter(None, sections))

    def _random_element(self, s):
        if len(s) <= 0:
            return ""
        return self.random.choice(s)
