import pytest

from meya.shopify.payload.order import Order


@pytest.mark.parametrize(
    "order",
    [
        (
            {
                "id": 3247449047240,
                "name": "#1005",
                "note": "",
                "tags": "",
                "test": True,
                "email": "joao_teste2@meya.ai",
                "phone": None,
                "token": "ec0759bbc2c856bd731a07116258a7dd",
                "app_id": 1354745,
                "number": 5,
                "gateway": "bogus",
                "refunds": [],
                "user_id": 69761204424,
                "currency": "BRL",
                "customer": {
                    "id": 4657113792712,
                    "note": "",
                    "tags": "",
                    "email": "joao_teste2@meya.ai",
                    "phone": None,
                    "state": "disabled",
                    "currency": "BRL",
                    "last_name": "teste 2 sobrenome",
                    "created_at": "2021-02-05T13:51:32-03:00",
                    "first_name": "test 2",
                    "tax_exempt": False,
                    "updated_at": "2021-02-05T13:54:05-03:00",
                    "total_spent": "0.00",
                    "orders_count": 0,
                    "last_order_id": None,
                    "tax_exemptions": [],
                    "verified_email": True,
                    "default_address": {
                        "id": 5684060258504,
                        "zip": "89040002",
                        "city": "Blumenau",
                        "name": "test 2 teste 2 sobrenome",
                        "phone": "",
                        "company": "",
                        "country": "Brazil",
                        "default": True,
                        "address1": "Rua dos caçadores 1111",
                        "address2": "apartment 2222",
                        "province": "Santa Catarina",
                        "last_name": "teste 2 sobrenome",
                        "first_name": "test 2",
                        "customer_id": 4657113792712,
                        "country_code": "BR",
                        "country_name": "Brazil",
                        "province_code": "SC",
                    },
                    "last_order_name": None,
                    "accepts_marketing": False,
                    "admin_graphql_api_id": "gid://shopify/Customer/4657113792712",
                    "multipass_identifier": None,
                    "marketing_opt_in_level": None,
                    "accepts_marketing_updated_at": "2021-02-05T13:51:32-03:00",
                },
                "closed_at": None,
                "confirmed": True,
                "device_id": None,
                "reference": None,
                "tax_lines": [
                    {
                        "rate": 0.17,
                        "price": "17.85",
                        "title": "VAT",
                        "price_set": {
                            "shop_money": {
                                "amount": "17.85",
                                "currency_code": "BRL",
                            },
                            "presentment_money": {
                                "amount": "17.85",
                                "currency_code": "BRL",
                            },
                        },
                    }
                ],
                "total_tax": "17.85",
                "browser_ip": "179.223.197.72",
                "cart_token": "",
                "created_at": "2021-02-05T13:54:05-03:00",
                "line_items": [
                    {
                        "id": 9221926650056,
                        "sku": "",
                        "name": "Network card",
                        "grams": 0,
                        "price": "105.00",
                        "title": "Network card",
                        "duties": [],
                        "vendor": "meyadev",
                        "taxable": True,
                        "quantity": 1,
                        "gift_card": False,
                        "price_set": {
                            "shop_money": {
                                "amount": "105.00",
                                "currency_code": "BRL",
                            },
                            "presentment_money": {
                                "amount": "105.00",
                                "currency_code": "BRL",
                            },
                        },
                        "tax_lines": [
                            {
                                "rate": 0.17,
                                "price": "17.85",
                                "title": "VAT",
                                "price_set": {
                                    "shop_money": {
                                        "amount": "17.85",
                                        "currency_code": "BRL",
                                    },
                                    "presentment_money": {
                                        "amount": "17.85",
                                        "currency_code": "BRL",
                                    },
                                },
                            }
                        ],
                        "product_id": 6219191091400,
                        "properties": [],
                        "variant_id": 37975221534920,
                        "variant_title": "",
                        "product_exists": True,
                        "total_discount": "0.00",
                        "origin_location": {
                            "id": 2714643071176,
                            "zip": "89031-004",
                            "city": "Blumenau",
                            "name": "meyadev",
                            "address1": "Rua Gustavo Salinger 47",
                            "address2": "apartment 1306",
                            "country_code": "BR",
                            "province_code": "SC",
                        },
                        "requires_shipping": True,
                        "fulfillment_status": None,
                        "total_discount_set": {
                            "shop_money": {
                                "amount": "0.00",
                                "currency_code": "BRL",
                            },
                            "presentment_money": {
                                "amount": "0.00",
                                "currency_code": "BRL",
                            },
                        },
                        "fulfillment_service": "manual",
                        "admin_graphql_api_id": "gid://shopify/LineItem/9221926650056",
                        "destination_location": {
                            "id": 2719141003464,
                            "zip": "89040002",
                            "city": "Blumenau",
                            "name": "test 2 teste 2 sobrenome",
                            "address1": "Rua dos caçadores 1111",
                            "address2": "apartment 2222",
                            "country_code": "BR",
                            "province_code": "SC",
                        },
                        "discount_allocations": [],
                        "fulfillable_quantity": 1,
                        "variant_inventory_management": "shopify",
                    }
                ],
                "source_url": None,
                "updated_at": "2021-02-05T13:54:06-03:00",
                "checkout_id": 19136608895176,
                "location_id": None,
                "source_name": "shopify_draft_order",
                "total_price": "122.85",
                "cancelled_at": None,
                "fulfillments": [],
                "landing_site": None,
                "order_number": 1005,
                "processed_at": "2021-02-05T13:53:59-03:00",
                "total_weight": 0,
                "cancel_reason": None,
                "contact_email": "joao_teste2@meya.ai",
                "total_tax_set": {
                    "shop_money": {"amount": "17.85", "currency_code": "BRL"},
                    "presentment_money": {
                        "amount": "17.85",
                        "currency_code": "BRL",
                    },
                },
                "checkout_token": "d4ff99da9fa7e93854615702b3f5f01e",
                "client_details": {
                    "browser_ip": "179.223.197.72",
                    "user_agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36",
                    "session_hash": None,
                    "browser_width": None,
                    "browser_height": None,
                    "accept_language": "en-US,en;q=0.9",
                },
                "discount_codes": [],
                "referring_site": None,
                "shipping_lines": [
                    {
                        "id": 2709372010696,
                        "code": "Standard",
                        "phone": None,
                        "price": "0.00",
                        "title": "Standard",
                        "source": "shopify",
                        "price_set": {
                            "shop_money": {
                                "amount": "0.00",
                                "currency_code": "BRL",
                            },
                            "presentment_money": {
                                "amount": "0.00",
                                "currency_code": "BRL",
                            },
                        },
                        "tax_lines": [],
                        "discounted_price": "0.00",
                        "delivery_category": None,
                        "carrier_identifier": None,
                        "discount_allocations": [],
                        "discounted_price_set": {
                            "shop_money": {
                                "amount": "0.00",
                                "currency_code": "BRL",
                            },
                            "presentment_money": {
                                "amount": "0.00",
                                "currency_code": "BRL",
                            },
                        },
                        "requested_fulfillment_service_id": None,
                    }
                ],
                "subtotal_price": "105.00",
                "taxes_included": False,
                "billing_address": {
                    "zip": "89040002",
                    "city": "Blumenau",
                    "name": "test 2 teste 2 sobrenome",
                    "phone": None,
                    "company": None,
                    "country": "Brazil",
                    "address1": "Rua dos caçadores 1111",
                    "address2": "apartment 2222",
                    "latitude": None,
                    "province": "Santa Catarina",
                    "last_name": "teste 2 sobrenome",
                    "longitude": None,
                    "first_name": "test 2",
                    "country_code": "BR",
                    "province_code": "SC",
                },
                "customer_locale": None,
                "note_attributes": [],
                "payment_details": {
                    "avs_result_code": None,
                    "credit_card_bin": "1",
                    "cvv_result_code": None,
                    "credit_card_number": "•••• •••• •••• 1",
                    "credit_card_company": "Bogus",
                },
                "total_discounts": "0.00",
                "total_price_set": {
                    "shop_money": {"amount": "122.85", "currency_code": "BRL"},
                    "presentment_money": {
                        "amount": "122.85",
                        "currency_code": "BRL",
                    },
                },
                "total_price_usd": "22.64",
                "financial_status": "paid",
                "landing_site_ref": None,
                "order_status_url": "https://meyadev.myshopify.com/53374124232/orders/ec0759bbc2c856bd731a07116258a7dd/authenticate?key=d6f1cc1999d6bd0f29d8cd4e30d2d36e",
                "shipping_address": {
                    "zip": "89040002",
                    "city": "Blumenau",
                    "name": "test 2 teste 2 sobrenome",
                    "phone": None,
                    "company": None,
                    "country": "Brazil",
                    "address1": "Rua dos caçadores 1111",
                    "address2": "apartment 2222",
                    "latitude": None,
                    "province": "Santa Catarina",
                    "last_name": "teste 2 sobrenome",
                    "longitude": None,
                    "first_name": "test 2",
                    "country_code": "BR",
                    "province_code": "SC",
                },
                "processing_method": "direct",
                "source_identifier": None,
                "fulfillment_status": None,
                "subtotal_price_set": {
                    "shop_money": {"amount": "105.00", "currency_code": "BRL"},
                    "presentment_money": {
                        "amount": "105.00",
                        "currency_code": "BRL",
                    },
                },
                "total_tip_received": "0.0",
                "total_discounts_set": {
                    "shop_money": {"amount": "0.00", "currency_code": "BRL"},
                    "presentment_money": {
                        "amount": "0.00",
                        "currency_code": "BRL",
                    },
                },
                "admin_graphql_api_id": "gid://shopify/Order/3247449047240",
                "presentment_currency": "BRL",
                "discount_applications": [],
                "payment_gateway_names": ["bogus"],
                "total_line_items_price": "105.00",
                "buyer_accepts_marketing": False,
                "current_total_duties_set": None,
                "total_shipping_price_set": {
                    "shop_money": {"amount": "0.00", "currency_code": "BRL"},
                    "presentment_money": {
                        "amount": "0.00",
                        "currency_code": "BRL",
                    },
                },
                "original_total_duties_set": None,
                "total_line_items_price_set": {
                    "shop_money": {"amount": "105.00", "currency_code": "BRL"},
                    "presentment_money": {
                        "amount": "105.00",
                        "currency_code": "BRL",
                    },
                },
            }
        ),
        (
            {
                "id": 3247446720712,
                "name": "#1004",
                "note": "",
                "tags": "",
                "test": True,
                "email": "joao_teste2@meya.ai",
                "phone": None,
                "token": "f5d0739c0deae065a7e04d18b43a27b8",
                "app_id": 1354745,
                "number": 4,
                "gateway": "bogus",
                "refunds": [],
                "user_id": 69761204424,
                "currency": "BRL",
                "customer": {
                    "id": 4657113792712,
                    "note": "",
                    "tags": "",
                    "email": "joao_teste2@meya.ai",
                    "phone": None,
                    "state": "disabled",
                    "currency": "BRL",
                    "last_name": "teste 2 sobrenome",
                    "created_at": "2021-02-05T13:51:32-03:00",
                    "first_name": "test 2",
                    "tax_exempt": False,
                    "updated_at": "2021-02-05T13:54:05-03:00",
                    "total_spent": "0.00",
                    "orders_count": 0,
                    "last_order_id": None,
                    "tax_exemptions": [],
                    "verified_email": True,
                    "default_address": {
                        "id": 5684060258504,
                        "zip": "89040002",
                        "city": "Blumenau",
                        "name": "test 2 teste 2 sobrenome",
                        "phone": "",
                        "company": "",
                        "country": "Brazil",
                        "default": True,
                        "address1": "Rua dos caçadores 1111",
                        "address2": "apartment 2222",
                        "province": "Santa Catarina",
                        "last_name": "teste 2 sobrenome",
                        "first_name": "test 2",
                        "customer_id": 4657113792712,
                        "country_code": "BR",
                        "country_name": "Brazil",
                        "province_code": "SC",
                    },
                    "last_order_name": None,
                    "accepts_marketing": False,
                    "admin_graphql_api_id": "gid://shopify/Customer/4657113792712",
                    "multipass_identifier": None,
                    "marketing_opt_in_level": None,
                    "accepts_marketing_updated_at": "2021-02-05T13:51:32-03:00",
                },
                "closed_at": None,
                "confirmed": True,
                "device_id": None,
                "reference": None,
                "tax_lines": [
                    {
                        "rate": 0.17,
                        "price": "2550.00",
                        "title": "VAT",
                        "price_set": {
                            "shop_money": {
                                "amount": "2550.00",
                                "currency_code": "BRL",
                            },
                            "presentment_money": {
                                "amount": "2550.00",
                                "currency_code": "BRL",
                            },
                        },
                    }
                ],
                "total_tax": "2550.00",
                "browser_ip": "179.223.197.72",
                "cart_token": "",
                "created_at": "2021-02-05T13:53:06-03:00",
                "line_items": [
                    {
                        "id": 9221921439944,
                        "sku": "",
                        "name": "GTX 3090",
                        "grams": 100,
                        "price": "15000.00",
                        "title": "GTX 3090",
                        "duties": [],
                        "vendor": "meyadev",
                        "taxable": True,
                        "quantity": 1,
                        "gift_card": False,
                        "price_set": {
                            "shop_money": {
                                "amount": "15000.00",
                                "currency_code": "BRL",
                            },
                            "presentment_money": {
                                "amount": "15000.00",
                                "currency_code": "BRL",
                            },
                        },
                        "tax_lines": [
                            {
                                "rate": 0.17,
                                "price": "2550.00",
                                "title": "VAT",
                                "price_set": {
                                    "shop_money": {
                                        "amount": "2550.00",
                                        "currency_code": "BRL",
                                    },
                                    "presentment_money": {
                                        "amount": "2550.00",
                                        "currency_code": "BRL",
                                    },
                                },
                            }
                        ],
                        "product_id": 6219189092552,
                        "properties": [],
                        "variant_id": 37975218716872,
                        "variant_title": "",
                        "product_exists": True,
                        "total_discount": "0.00",
                        "origin_location": {
                            "id": 2714643071176,
                            "zip": "89031-004",
                            "city": "Blumenau",
                            "name": "meyadev",
                            "address1": "Rua Gustavo Salinger 47",
                            "address2": "apartment 1306",
                            "country_code": "BR",
                            "province_code": "SC",
                        },
                        "requires_shipping": True,
                        "fulfillment_status": None,
                        "total_discount_set": {
                            "shop_money": {
                                "amount": "0.00",
                                "currency_code": "BRL",
                            },
                            "presentment_money": {
                                "amount": "0.00",
                                "currency_code": "BRL",
                            },
                        },
                        "fulfillment_service": "manual",
                        "admin_graphql_api_id": "gid://shopify/LineItem/9221921439944",
                        "destination_location": {
                            "id": 2719141003464,
                            "zip": "89040002",
                            "city": "Blumenau",
                            "name": "test 2 teste 2 sobrenome",
                            "address1": "Rua dos caçadores 1111",
                            "address2": "apartment 2222",
                            "country_code": "BR",
                            "province_code": "SC",
                        },
                        "discount_allocations": [],
                        "fulfillable_quantity": 1,
                        "variant_inventory_management": "shopify",
                    }
                ],
                "source_url": None,
                "updated_at": "2021-02-05T13:53:08-03:00",
                "checkout_id": 19136597786824,
                "location_id": None,
                "source_name": "shopify_draft_order",
                "total_price": "17550.00",
                "cancelled_at": None,
                "fulfillments": [],
                "landing_site": None,
                "order_number": 1004,
                "processed_at": "2021-02-05T13:53:02-03:00",
                "total_weight": 100,
                "cancel_reason": None,
                "contact_email": "joao_teste2@meya.ai",
                "total_tax_set": {
                    "shop_money": {
                        "amount": "2550.00",
                        "currency_code": "BRL",
                    },
                    "presentment_money": {
                        "amount": "2550.00",
                        "currency_code": "BRL",
                    },
                },
                "checkout_token": "66f42504b4f263eb370f82109cf76a44",
                "client_details": {
                    "browser_ip": "179.223.197.72",
                    "user_agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36",
                    "session_hash": None,
                    "browser_width": None,
                    "browser_height": None,
                    "accept_language": "en-US,en;q=0.9",
                },
                "discount_codes": [],
                "referring_site": None,
                "shipping_lines": [],
                "subtotal_price": "15000.00",
                "taxes_included": False,
                "billing_address": {
                    "zip": "89040002",
                    "city": "Blumenau",
                    "name": "test 2 teste 2 sobrenome",
                    "phone": None,
                    "company": None,
                    "country": "Brazil",
                    "address1": "Rua dos caçadores 1111",
                    "address2": "apartment 2222",
                    "latitude": None,
                    "province": "Santa Catarina",
                    "last_name": "teste 2 sobrenome",
                    "longitude": None,
                    "first_name": "test 2",
                    "country_code": "BR",
                    "province_code": "SC",
                },
                "customer_locale": None,
                "note_attributes": [],
                "payment_details": {
                    "avs_result_code": None,
                    "credit_card_bin": "1",
                    "cvv_result_code": None,
                    "credit_card_number": "•••• •••• •••• 1",
                    "credit_card_company": "Bogus",
                },
                "total_discounts": "0.00",
                "total_price_set": {
                    "shop_money": {
                        "amount": "17550.00",
                        "currency_code": "BRL",
                    },
                    "presentment_money": {
                        "amount": "17550.00",
                        "currency_code": "BRL",
                    },
                },
                "total_price_usd": "3233.85",
                "financial_status": "paid",
                "landing_site_ref": None,
                "order_status_url": "https://meyadev.myshopify.com/53374124232/orders/f5d0739c0deae065a7e04d18b43a27b8/authenticate?key=220e1cce847b53dd13ca4c36792c34b7",
                "shipping_address": {
                    "zip": "89040002",
                    "city": "Blumenau",
                    "name": "test 2 teste 2 sobrenome",
                    "phone": None,
                    "company": None,
                    "country": "Brazil",
                    "address1": "Rua dos caçadores 1111",
                    "address2": "apartment 2222",
                    "latitude": None,
                    "province": "Santa Catarina",
                    "last_name": "teste 2 sobrenome",
                    "longitude": None,
                    "first_name": "test 2",
                    "country_code": "BR",
                    "province_code": "SC",
                },
                "processing_method": "direct",
                "source_identifier": None,
                "fulfillment_status": None,
                "subtotal_price_set": {
                    "shop_money": {
                        "amount": "15000.00",
                        "currency_code": "BRL",
                    },
                    "presentment_money": {
                        "amount": "15000.00",
                        "currency_code": "BRL",
                    },
                },
                "total_tip_received": "0.0",
                "total_discounts_set": {
                    "shop_money": {"amount": "0.00", "currency_code": "BRL"},
                    "presentment_money": {
                        "amount": "0.00",
                        "currency_code": "BRL",
                    },
                },
                "admin_graphql_api_id": "gid://shopify/Order/3247446720712",
                "presentment_currency": "BRL",
                "discount_applications": [],
                "payment_gateway_names": ["bogus"],
                "total_line_items_price": "15000.00",
                "buyer_accepts_marketing": False,
                "current_total_duties_set": None,
                "total_shipping_price_set": {
                    "shop_money": {"amount": "0.00", "currency_code": "BRL"},
                    "presentment_money": {
                        "amount": "0.00",
                        "currency_code": "BRL",
                    },
                },
                "original_total_duties_set": None,
                "total_line_items_price_set": {
                    "shop_money": {
                        "amount": "15000.00",
                        "currency_code": "BRL",
                    },
                    "presentment_money": {
                        "amount": "15000.00",
                        "currency_code": "BRL",
                    },
                },
            }
        ),
    ],
)
def test_customer_orders_test(order):
    try:
        Order.from_dict(order)
        assert True
    except Exception:
        assert False
